### ISSUE TITLE
somthing about calculate PSNR

### ISSUE THREAD

**Issue by cassiopeiaip** [jiny2001/dcscn-super-resolution#13]
I have ran your model,but it gives me lower PSNR values in comparison to ones mentioned in READ.md file . I am bit confused if I am understanding something wrong or whats wrong that I am not getting the reported values.The data gap with the article is about 1dB.

**Comment by jiny2001** [comment]
Hi,

1dB is a big thing. Which command and args did you run? I'll check it.

**Comment by cassiopeiaip** [comment]
dataset is yang91 without data augment.the args has not changed,and command is python train.py .

**Comment by jiny2001** [comment]
OK.

Yang91 is really small dataset. You can't have a nice PSNR with that.
I use yang91 + BSD200 with augmentation. 
BSD200 and augmentation(x4) significantly improves the result. Please try it.

Best,

**Comment by cassiopeiaip** [comment]
OK，I use your method to measure it, which is 0.1 lower than the value in the paper. Is this allowed within the permissible error, or there are some parameters that need to be adjusted.

**Comment by jiny2001** [comment]
Hi,
I feel 0.1 is not an ignorable difference.

However, since it's based on randomness, the PSNR result easily fluctuates between 0.01 to 0.1 .
I usually try at least 3 times and use mean value to evaluate.

Or if you are comparing with the result PSNR on my paper, it may be little different. There is an issue about that. Please check below.
https://github.com/jiny2001/dcscn-super-resolution/issues/9

Hope those helps you.

**Comment by cassiopeiaip** [comment]
Thank you very much for answering my questions in your busy schedule.
