### ISSUE TITLE
Split images tricks ?

### ISSUE THREAD

**Issue by phongnhhn92** [jiny2001/dcscn-super-resolution#15]
Hello sir, 
I am quite impress with your paper results and i am trying to implement it for my project. However I have a question related to the build_batch function in the loader.py.
![screenshot from 2018-04-12 19-20-27](https://user-images.githubusercontent.com/11288381/38651245-11513d98-3e3b-11e8-9f78-726049a068fd.png)
I read your paper and i see you have never mentioned about splitting the input image into smaller batches. I am confusing that you are using the whole low resolution image or the small batch image (crop from the original low resolution image) as input to your CNN. Can you explain it for me ? Thank you !

**Comment by jiny2001** [comment]
Well,

In section 4 of my paper, I mentioned like
"Each training image is split into 32 by 32 patches with stride 16 and 64 patches are used
as a mini-batch".

However, making small patches is quite common for training SR or other Computer Vision models.

If you use whole images and the image is not small, you feed a lot of similar patches in a same time. Which is not good for generalization I believe. So usually they split it and shuffle with other images and then feed it. 

But you can try with using whole image instead of small patches and will see the difference. I'm quite interested in that also. Thank you.
