### ISSUE TITLE
some questions ablut training my own data.

### ISSUE THREAD

**Issue by wehkjhkl** [jiny2001/dcscn-super-resolution#41]
I am using your network to train my own data  in the field of public security,for exmple,license plate number.while when I downsample the picture that the number can not be seen clearly. It seems bad performance when I use trained model to upsample it .Do you have any advice?

**Comment by rafariva** [comment]
How big is your dataset? what params (layers,filters,etc)  are you using for training your model?

**Comment by wehkjhkl** [comment]
my dataset is 390*4(augmentation),I use the default params and the command python train.py --dataset=mydata --training_images=80000 to run the code

**Comment by wehkjhkl** [comment]
@rafariva

**Comment by rafariva** [comment]
And the default size (resolution) of your images? Of 390*4, how many for test?
Maybe tray batch=True  (dont remember the exact param batch)

**Comment by jiny2001** [comment]
Hi, sorry I haven't noticed your issue.
Is your dataset from moving cars? If so, I recommend you to check if there are motion blur. If they have a blur, the problem is more difficult and I think you need to take blur first.

For my training, I use 300 x (480x320) images x (2 to 8 augmentations).
Please note, if you want to make it double resolution, you need to used doubled resolution as your GT(training data). I mean, if you want to make 200 pix image to 400 pix, you have to train with 400 pix image as your dataset. Don't use 200 pix image as your training dataset.

**Comment by wehkjhkl** [comment]
If I train with 400 pix image as my dataset, Do you think it is possibleto make 20 pix image to 40? @jiny2001

**Comment by jiny2001** [comment]
I mean, it is not about the resolution itself.

Let's say, I have a 400pix and the license plate which is in the pic has 400 pix width (the plate's left and right edges are just on a image boundary), we can train a model something like 200 width license plate to 400 width license plate. You can train whatever from 100/200/300 to 400 width.

In that case, if you have a 20pix image which is a part of 400pix width license plate, it will work fine.

**Comment by wehkjhkl** [comment]
thank you!I understand it @jiny2001
