### ISSUE TITLE
low GPU utilization rate

### ISSUE THREAD

**Issue by GengDavid** [jiny2001/dcscn-super-resolution#48]
Hi, @jiny2001 
I'm trying to train compact version of DCSCN. But I found that the GPU utilization rate is very unstable. It seems that GPU is waiting for CPU to feed data. Have you encounter this problem while training? 
My training process takes 1.841sec/step. Is this a normal condition? Could you share some training log with me?
Thx.

**Comment by jiny2001** [comment]
Hi,
Training speed really depends on the environment. I'm using linux with GTX1080Ti and the time is 0.247 sec/step for yang_bsd_8, build_batch=True, 12 layers with 196 filters.
When I use 9 layers with 96 filters, the training time can be half.

I can share a log file but which condition do you want?

**Comment by GengDavid** [comment]
I‘m training with the compact version you provide.
```python train.py --scale=2 --layers=7 --filters=32 --min_filters=8 --filters_decay_gamma=1.2 --nin_filters=24 --nin_filters2=8 --reconstruct_layers=0 --self_ensemble=1 --dataset=yang_bsd_8 --training_images=228688 --batch_image_size=32 --do_benchmark=True --pixel_shuffler_filters=1```
But I remove ```build_batch``` option in my experiment. But it's also nice to have log file of this configuration so that I can refer to it to check around.
Thanks!

**Comment by jiny2001** [comment]
Hi I believe you should use build_batch=true otherwise, the trainer load png/jpeg, convert it to Y and crop/reflect it to every patch. This is so slow. At least you should convert it to y_image prior to the training I feel.

So, in my environment without build_patch, the processing time(including data loading) is 0.153 sec/step (I put the log below). And for with build_batch, the time was 0.015 sec/step.

DCSCN v2-------------------------------------
2018/8/4 14:4:25 [dcscn_L7_F32to8_G1.20_NIN_A24_B8_PS_R1F32]
Feature:32 26 22 18 14 11 8  Total: (131)24 8 8 4 1  Complexity:27,209 Receptive Fields:19
CNN1/conv_W:0 (3, 3, 1, 32)=288, CNN1/conv_B:0 32, CNN1/prelu/CNN1_prelu:0 32, CNN2/conv_W:0 (3, 3, 32, 26)=7488, CNN2/conv_B:0 26, CNN2/prelu/CNN2_prelu:0 26, CNN3/conv_W:0 (3, 3, 26, 22)=5148, CNN3/conv_B:0 22, CNN3/prelu/CNN3_prelu:0 22, CNN4/conv_W:0 (3, 3, 22, 18)=3564, CNN4/conv_B:0 18, CNN4/prelu/CNN4_prelu:0 18, CNN5/conv_W:0 (3, 3, 18, 14)=2268, CNN5/conv_B:0 14, CNN5/prelu/CNN5_prelu:0 14, CNN6/conv_W:0 (3, 3, 14, 11)=1386, CNN6/conv_B:0 11, CNN6/prelu/CNN6_prelu:0 11, CNN7/conv_W:0 (3, 3, 11, 8)=792, CNN7/conv_B:0 8, CNN7/prelu/CNN7_prelu:0 8, A1/conv_W:0 (1, 1, 131, 24)=3144, A1/conv_B:0 24, A1/prelu/A1_prelu:0 24, B1/conv_W:0 (1, 1, 131, 8)=1048, B1/conv_B:0 8, B1/prelu/B1_prelu:0 8, B2/conv_W:0 (3, 3, 8, 8)=576, B2/conv_B:0 8, B2/prelu/B2_prelu:0 8, Up-PS/Up-PS_CNN/conv_W:0 (3, 3, 32, 4)=1152, Up-PS/Up-PS_CNN/conv_B:0 4, R-CNN1/conv_W:0 (3, 3, 1, 1)=9, 
Total 33 variables, 27,209 params

['train.py', '--scale=2', '--layers=7', '--filters=32', '--min_filters=8', '--filters_decay_gamma=1.2', '--nin_filters=24', '--nin_filters2=8', '--reconstruct_layers=0', '--self_ensemble=1', '--dataset=yang_bsd_8', '--training_images=228688', '--batch_image_size=32', '--do_benchmark=True', '--pixel_shuffler_filters=1']
Test Data:set5 Training Data:yang_bsd_8
Total 33 variables, 27,209 params
Model initialized.
Initial MSE:3914.054226 PSNR:12.279134
2018/8/4 14:34:41 Step:11,435 MSE:16.191780 PSNR:36.918997 (Training PSNR:30.452)
Epoch:1 LR:0.002000 (0.157sec/step) Estimated:30:59:3
Model saved [models/dcscn_L7_F32to8_G1.20_NIN_A24_B8_PS_R1F32.ckpt].
2018/8/4 15:3:38 Step:22,870 MSE:15.968865 PSNR:36.964740 (Training PSNR:30.590)
Epoch:2 LR:0.002000 (0.155sec/step) Estimated:29:57:46
Model saved [models/dcscn_L7_F32to8_G1.20_NIN_A24_B8_PS_R1F32.ckpt].
2018/8/4 15:32:37 Step:34,305 MSE:15.939032 PSNR:36.985076 (Training PSNR:30.598)
Epoch:3 LR:0.002000 (0.154sec/step) Estimated:29:18:24
Model saved [models/dcscn_L7_F32to8_G1.20_NIN_A24_B8_PS_R1F32.ckpt].
2018/8/4 16:1:35 Step:45,740 MSE:15.919094 PSNR:36.933910 (Training PSNR:30.633)
Epoch:4 LR:0.002000 (0.153sec/step) Estimated:28:44:3
Model saved [models/dcscn_L7_F32to8_G1.20_NIN_A24_B8_PS_R1F32.ckpt].

**Comment by GengDavid** [comment]
Thanks! ```build_batch``` option is the key point.
