### ISSUE TITLE
use_NIN

### ISSUE THREAD

**Issue by rafariva** [jiny2001/dcscn-super-resolution#67]
Hi, when set use_nin = False, get error in trainning.  i though was my memory, but already try with few filters, and layers, and batch. always this error

![image](https://user-images.githubusercontent.com/26292862/51494938-85428e00-1d88-11e9-9037-6d2113799bdd.png)

**Comment by jiny2001** [comment]
Oops, sorry for late reply. I had a business trip these days.

It looks it happening because of memory issue. Could you give me python command line args which you are trying? I'll quickly check it in my environment.

**Comment by rafariva** [comment]
Hi, i dont think is memory issue, the command line is: (if i dont use nin, it should not need to much memory)

py train.py --dataset=thermal_new_8 --test_dataset=thermal_test --scale=4 --layers=8 --filters=96 --training_images=1000 --batch_num=20 --lr_decay=0.35 --use_nin=False

**Comment by jiny2001** [comment]
Yea, you are right. I tried with --use_nin=False and it resulted in resource error. But when I tried with -use_nin=True, it worked. 

So I found the cause is use_nin option. Will check the detail soon. Thx!

**Comment by jiny2001** [comment]
Hi, sorry for late reply.
I found that the model don't reduce the num of nodes before upsampling when we don't use NIN layer.

In this way, for ex num of nodes is 540 before the upsampling and the total num of nodes gets 4 x 4 x 540 = 8,640 after upsampling. And the huge memory is consumed at that layer.

I added dim reduction CNN so that it reduces num nodes from 540 to 96 in your case. I updated the repo so please try when you have a time.

BTW, I believe when you use scale of 4, it might be better to try smaller batch_image_size. Thx!
